// @generated
// This file is @generated by prost-build.
/// Everything the registry emitted in one block, on one chain.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentRegistrations {
    /// CAIP-2 chain identifier, e.g. "eip155:1".
    #[prost(string, tag="1")]
    pub chain: ::prost::alloc::string::String,
    /// Numeric EVM chain id, e.g. 1 or 8453.
    #[prost(uint64, tag="2")]
    pub chain_id: u64,
    /// Substreams network name the module ran against, e.g. "mainnet", "base".
    #[prost(string, tag="3")]
    pub network: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub block_number: u64,
    #[prost(string, tag="5")]
    pub block_hash: ::prost::alloc::string::String,
    /// Unix seconds.
    #[prost(int64, tag="6")]
    pub block_timestamp: i64,
    #[prost(message, repeated, tag="7")]
    pub registrations: ::prost::alloc::vec::Vec<AgentRegistration>,
    /// `agentWallet` metadata changes seen in this block. Emitted separately
    /// because an agent can repoint its payout address without ever touching its
    /// URI, so these do not always coincide with an AgentRegistration row.
    #[prost(message, repeated, tag="8")]
    pub wallet_updates: ::prost::alloc::vec::Vec<AgentWalletUpdate>,
}
/// The reserved `agentWallet` metadata key changing for an agent.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentWalletUpdate {
    #[prost(string, tag="1")]
    pub agent_uid: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub chain_id: u64,
    #[prost(string, tag="3")]
    pub network: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub registry: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub agent_id: ::prost::alloc::string::String,
    /// New payout address, lowercase 0x-hex.
    #[prost(string, tag="6")]
    pub wallet: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub block_number: u64,
    #[prost(int64, tag="8")]
    pub block_timestamp: i64,
    #[prost(string, tag="9")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub log_index: u32,
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
}
/// A single agent as of one registry event.
///
/// `REGISTERED` rows are the agent's first appearance; `URI_UPDATED` rows carry
/// the same identity with a new service document. A consumer that wants "current
/// state" keeps the highest (block_number, log_index) per `agent_uid`.
///
/// ---- identity -----------------------------------------------------------
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentRegistration {
    /// Globally unique agent identifier, CAIP-10-shaped and extended with the
    /// ERC-721 token id: "eip155:<chain_id>:<registry>/<agent_id>".
    /// This is the key to join on across chains.
    #[prost(string, tag="1")]
    pub agent_uid: ::prost::alloc::string::String,
    /// CAIP-2 namespace. Always "eip155" for the EVM registries.
    #[prost(string, tag="2")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub chain_id: u64,
    #[prost(string, tag="4")]
    pub network: ::prost::alloc::string::String,
    /// ERC-8004 Identity Registry contract, lowercase 0x-hex.
    #[prost(string, tag="5")]
    pub registry: ::prost::alloc::string::String,
    /// ERC-721 tokenId assigned incrementally by the registry, as a decimal
    /// string because it is a uint256.
    #[prost(string, tag="6")]
    pub agent_id: ::prost::alloc::string::String,
    // ---- control ------------------------------------------------------------

    /// ERC-721 owner of the agent token at the time of this event.
    #[prost(string, tag="7")]
    pub owner: ::prost::alloc::string::String,
    /// The `agentWallet` reserved metadata key: the address the agent is paid at.
    /// EIP-8004 initialises it to the owner, so this falls back to `owner` when no
    /// `agentWallet` has been set in or before this block. `operator_source` says
    /// which it was.
    #[prost(string, tag="8")]
    pub operator: ::prost::alloc::string::String,
    #[prost(enumeration="OperatorSource", tag="9")]
    pub operator_source: i32,
    // ---- service document ---------------------------------------------------

    /// Raw tokenURI as emitted. May be empty, ipfs://, <https://,> a data: URI, or
    /// (non-conformantly, but it happens) a bare JSON literal.
    #[prost(string, tag="10")]
    pub agent_uri: ::prost::alloc::string::String,
    #[prost(enumeration="UriScheme", tag="11")]
    pub uri_scheme: i32,
    /// True when the registration document was inline in the URI and this module
    /// parsed it, so the fields below are populated. False for ipfs:// and
    /// https:// URIs, which need an off-chain fetch this module cannot perform
    /// deterministically — see README, "What is and is not resolved on-chain".
    #[prost(bool, tag="12")]
    pub registration_resolved: bool,
    #[prost(string, tag="13")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub image: ::prost::alloc::string::String,
    /// EIP-8004 registration-v1 `services` (some agents emit `endpoints`; both are
    /// read into this field).
    #[prost(message, repeated, tag="16")]
    pub endpoints: ::prost::alloc::vec::Vec<Endpoint>,
    #[prost(bool, tag="17")]
    pub x402_support: bool,
    #[prost(bool, tag="18")]
    pub active: bool,
    /// e.g. \["reputation", "crypto-economic", "tee-attestation"\].
    #[prost(string, repeated, tag="19")]
    pub supported_trust: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Advertised price, when the agent publishes one. Usually absent: see README.
    #[prost(message, optional, tag="20")]
    pub price: ::core::option::Option<Price>,
    // ---- provenance ---------------------------------------------------------

    #[prost(enumeration="RegistrationEvent", tag="21")]
    pub event: i32,
    #[prost(uint64, tag="22")]
    pub block_number: u64,
    #[prost(int64, tag="23")]
    pub block_timestamp: i64,
    #[prost(string, tag="24")]
    pub transaction_hash: ::prost::alloc::string::String,
    /// Index of the log within the block.
    #[prost(uint32, tag="25")]
    pub log_index: u32,
    #[prost(uint64, tag="26")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Endpoint {
    /// Endpoint role, e.g. "web", "A2A", "MCP", "x402".
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub uri: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub version: ::prost::alloc::string::String,
    /// OASF skill / domain tags, when present.
    #[prost(string, repeated, tag="4")]
    pub skills: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="5")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// A price the agent advertises in its registration document.
///
/// EIP-8004 registration-v1 does not standardise a price field — under x402 the
/// quote is returned dynamically by the endpoint in an HTTP 402 response. This
/// message therefore captures the non-standard `price` objects some agents do
/// publish, shaped like an x402 payment requirement so the two line up.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Price {
    /// Decimal string in the asset's smallest unit when `asset` is set, otherwise
    /// as published.
    #[prost(string, tag="1")]
    pub amount: ::prost::alloc::string::String,
    /// Human-readable currency code, e.g. "USDC".
    #[prost(string, tag="2")]
    pub currency: ::prost::alloc::string::String,
    /// Token contract address, when the document names one.
    #[prost(string, tag="3")]
    pub asset: ::prost::alloc::string::String,
    /// Settlement network as published, e.g. "base".
    #[prost(string, tag="4")]
    pub network: ::prost::alloc::string::String,
    /// Payment scheme, e.g. "exact".
    #[prost(string, tag="5")]
    pub scheme: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RegistrationEvent {
    Unspecified = 0,
    Registered = 1,
    UriUpdated = 2,
}
impl RegistrationEvent {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            RegistrationEvent::Unspecified => "REGISTRATION_EVENT_UNSPECIFIED",
            RegistrationEvent::Registered => "REGISTRATION_EVENT_REGISTERED",
            RegistrationEvent::UriUpdated => "REGISTRATION_EVENT_URI_UPDATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REGISTRATION_EVENT_UNSPECIFIED" => Some(Self::Unspecified),
            "REGISTRATION_EVENT_REGISTERED" => Some(Self::Registered),
            "REGISTRATION_EVENT_URI_UPDATED" => Some(Self::UriUpdated),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OperatorSource {
    Unspecified = 0,
    /// No agentWallet seen; operator == owner, per the EIP-8004 default.
    OwnerDefault = 1,
    /// Taken from an `agentWallet` MetadataSet event.
    AgentWallet = 2,
}
impl OperatorSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            OperatorSource::Unspecified => "OPERATOR_SOURCE_UNSPECIFIED",
            OperatorSource::OwnerDefault => "OPERATOR_SOURCE_OWNER_DEFAULT",
            OperatorSource::AgentWallet => "OPERATOR_SOURCE_AGENT_WALLET",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPERATOR_SOURCE_UNSPECIFIED" => Some(Self::Unspecified),
            "OPERATOR_SOURCE_OWNER_DEFAULT" => Some(Self::OwnerDefault),
            "OPERATOR_SOURCE_AGENT_WALLET" => Some(Self::AgentWallet),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UriScheme {
    Unspecified = 0,
    Empty = 1,
    Data = 2,
    Ipfs = 3,
    Https = 4,
    Http = 5,
    /// A bare JSON literal in the URI field.
    InlineJson = 6,
    Other = 7,
}
impl UriScheme {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            UriScheme::Unspecified => "URI_SCHEME_UNSPECIFIED",
            UriScheme::Empty => "URI_SCHEME_EMPTY",
            UriScheme::Data => "URI_SCHEME_DATA",
            UriScheme::Ipfs => "URI_SCHEME_IPFS",
            UriScheme::Https => "URI_SCHEME_HTTPS",
            UriScheme::Http => "URI_SCHEME_HTTP",
            UriScheme::InlineJson => "URI_SCHEME_INLINE_JSON",
            UriScheme::Other => "URI_SCHEME_OTHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "URI_SCHEME_UNSPECIFIED" => Some(Self::Unspecified),
            "URI_SCHEME_EMPTY" => Some(Self::Empty),
            "URI_SCHEME_DATA" => Some(Self::Data),
            "URI_SCHEME_IPFS" => Some(Self::Ipfs),
            "URI_SCHEME_HTTPS" => Some(Self::Https),
            "URI_SCHEME_HTTP" => Some(Self::Http),
            "URI_SCHEME_INLINE_JSON" => Some(Self::InlineJson),
            "URI_SCHEME_OTHER" => Some(Self::Other),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
