#!/usr/bin/env node
// Assemble a self-contained, installable tarball.
//
// Two problems, and the second one is the interesting one.
//
// ## 1. The sources live outside the package directory
//
// `server.ts` imports `../graph/sink/db.ts`, `../seller/service/discovery.ts`
// and a dozen more from elsewhere in the repository, and npm packs only what is
// under the package directory — a `files` list cannot reach a sibling.
//
// So this walks the import graph from the entry point and emits each file it
// finds into `_bundle/`, **mirroring the repository layout**: `_bundle/
// mcp-turnstile/server.js` importing `../graph/sink/db.js` lands on
// `_bundle/graph/sink/db.js`, with every relative specifier in the same place it
// was. The walk is why there is no hand-maintained file list — adding an import
// anywhere in the graph packs it, deleting one stops shipping it. The only
// manual part is `EXTRAS`, for files read at runtime rather than imported.
//
// ## 2. A published package cannot ship TypeScript, even though the repo runs it
//
// The repository has no build step: Node runs the `.ts` files directly, by type
// stripping, which has been on by default since 22.18. That does **not** extend
// to an installed dependency. Node refuses to strip types for anything under
// `node_modules` and throws `ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING`
// (verified 2026-09-07 on Node v26.7.0, by installing a `.ts`-bin tarball and
// running its `bin`). It is a deliberate rule, not a gap: a published package is
// expected to ship JavaScript.
//
// So packing compiles, and only packing. `rewriteRelativeImportExtensions` is
// already on in the repository's `tsconfig.json`, so `./db.ts` becomes `./db.js`
// on emit and nothing has to be rewritten by hand. Working in the repo is
// unaffected — `node mcp-turnstile/server.ts` still runs the sources.

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, relative, resolve } from 'node:path';

const PACKAGE_DIR = dirname(import.meta.dirname);
const REPO_ROOT = dirname(PACKAGE_DIR);
const BUNDLE = join(PACKAGE_DIR, '_bundle');
const TSCONFIG = join(REPO_ROOT, 'tsconfig.pack.json');

/** Everything the published `bin` can reach. */
const ENTRY_POINTS = ['mcp-turnstile/server.ts'];

/**
 * Read at runtime rather than imported, so the import walk cannot see them.
 *
 * `schema.sql` is `readFileSync`'d by `db.ts` on every open. The discovery
 * snapshot is what makes `npx mcp-turnstile` answer a real query on a machine
 * that has never run the sink — without it the server starts and finds nothing,
 * which is the exact failure mode `store.ts` exists to prevent.
 */
const EXTRAS = [
  'graph/sink/schema.sql',
  'web/data/discovery.db',
  'web/data/provenance.json',
];

/** Relative specifiers only. A bare specifier is a dependency npm installs. */
const RELATIVE_IMPORT = /(?:^|\n)\s*(?:import|export)[\s\S]*?from\s*['"](\.[^'"]+)['"]|import\s*\(\s*['"](\.[^'"]+)['"]\s*\)/g;

function importsOf(source) {
  const out = new Set();
  for (const match of source.matchAll(RELATIVE_IMPORT)) {
    const specifier = match[1] ?? match[2];
    if (specifier) out.add(specifier);
  }
  return out;
}

/** Depth-first over the import graph, returning repo-relative paths. */
function collect(entryPoints) {
  const seen = new Set();
  const queue = [...entryPoints];
  while (queue.length > 0) {
    const rel = queue.pop();
    if (seen.has(rel)) continue;
    const absolute = join(REPO_ROOT, rel);
    if (!existsSync(absolute)) throw new Error(`${rel} does not exist`);
    seen.add(rel);
    // A test file is not shipped, and must not drag its fixtures in either.
    if (rel.endsWith('.test.ts')) continue;
    for (const specifier of importsOf(readFileSync(absolute, 'utf8'))) {
      queue.push(relative(REPO_ROOT, resolve(dirname(absolute), specifier)));
    }
  }
  return [...seen].sort();
}

const sources = collect(ENTRY_POINTS);

rmSync(BUNDLE, { recursive: true, force: true });
writeFileSync(TSCONFIG, JSON.stringify({
  '//': 'Generated by mcp-turnstile/scripts/prepack.mjs. Deleted after packing.',
  extends: './tsconfig.json',
  compilerOptions: {
    noEmit: false,
    outDir: 'mcp-turnstile/_bundle',
    rootDir: '.',
    declaration: false,
    sourceMap: false,
  },
  // `extends` inherits the base config's `include`, and TypeScript takes the
  // UNION of `files` and `include` — so without this the whole repository
  // compiles into the tarball rather than the 25 files the server reaches.
  include: [],
  files: sources,
}, null, 2));

try {
  execFileSync('npx', ['tsc', '-p', TSCONFIG], { cwd: REPO_ROOT, stdio: 'inherit' });
} finally {
  rmSync(TSCONFIG, { force: true });
}

for (const rel of EXTRAS) {
  const target = join(BUNDLE, rel);
  mkdirSync(dirname(target), { recursive: true });
  cpSync(join(REPO_ROOT, rel), target);
}

// A note inside the tarball, so someone who unpacks it and wonders why the
// layout looks like a repository has the answer in front of them.
writeFileSync(join(BUNDLE, 'README.md'),
  '# _bundle\n\n' +
  'Generated by `mcp-turnstile/scripts/prepack.mjs`. It is the Turnstile sources\n' +
  'this server needs, compiled to JavaScript and laid out exactly as they are in\n' +
  'the repository, so every relative import resolves without rewriting.\n\n' +
  'Do not edit anything here — edit the sources and re-pack.\n\n' +
  `Compiled from ${sources.length} TypeScript files, plus ${EXTRAS.length} runtime assets.\n`);

process.stdout.write(`_bundle: ${sources.length} compiled + ${EXTRAS.length} copied\n`);
