import Link from 'next/link';

import { CreateMandate } from '../../../components/CreateMandate.tsx';

export const metadata = { title: 'Create a mandate · Turnstile' };

export default function NewMandatePage() {
  return (
    <div className="wrap seller">
      <div className="seller-head">
        <div>
          <p className="eyebrow">The warm tier · your own organization</p>
          <h1 className="seller-name">Create a mandate</h1>
        </div>
      </div>

      <p className="lede">
        A mandate lets an agent spend without holding the key that decides how much it may spend.
        This creates one: two humans, two quorums with different thresholds, a policy that caps the
        agent, and an organization wallet governed by that policy.
      </p>

      <section className="section">
        <div className="section-head">
          <h2 className="section-title">Where the keys live</h2>
        </div>
        <p className="section-note">
          Your operators&rsquo; signing keys are generated by <b>your browser</b> and never leave
          it. Only the public halves reach this server, because a Privy key quorum has never
          consumed anything else. That means the organization is created under our Privy app but is
          not ours to spend from: every mutation additionally needs a signature from keys we do not
          have. We are the registrar, not the custodian.
        </p>
        <p className="section-note">
          If you would rather not rely on us at all, the same flow exists as{' '}
          <span className="mono">npm run privy:setup</span> against your own Privy app. Either way
          you end with the same <span className="mono">.env</span> block and the same organization
          shape, and either way you can self-host from{' '}
          <Link href="https://github.com/IpastorSan/turnstile">the repository</Link>.
        </p>
      </section>

      <section className="section">
        <div className="section-head">
          <h2 className="section-title">The organization</h2>
        </div>
        <CreateMandate />
      </section>

      <section className="section">
        <p className="section-note">
          <Link href="/mandate">← The demo organization, read live</Link>
        </p>
      </section>
    </div>
  );
}
